### ISSUE TITLE
Skrollr library doesn't render

### ISSUE THREAD

**Issue by FajneFarita** [GA-MO/react-skrollr#5]
In a multipage React app, when navigating from container to container (page to page), and eventually clicking on a page with a skrollr animation, the Parallax data part seems not to load. Only when you refresh this page in the browser, everything takes its place and animation works.

**Comment by GA-MO** [comment]
@FajneFarita 
Did you wrap containers with `ParallaxProvider` ?
Try example for multipage https://stackblitz.com/edit/react-anfccw

**Comment by FajneFarita** [comment]
I did wrap the scenes with ParallaxProvider and initiated it like this:

```
<ParallaxProvider init={{smoothScrolling: true}}>
{/* Scene 1 */}
  <Parallax data={{'data-start': 'opacity: 1; position:fixed; left:45%;','data-top': 'opacity: 0;'}}>
    <div>Scroll to see the story</div>
  </Parallax>
 <Parallax data={{.....}}
    <div> ...</div>
  </Parallax>

 ....
</ParallaxProvider>
```
 
But I use <HashRouter> to navigate between containers (pages). My App.js is essentially a router, and it loads my parallax animation page (which is Howitworks.js) through:
```
<HashRouter>
  <Switch>
    <Route path="/howitworks" component={Howitworks}/>
  </Switch>
<HashRouter>
```

**Comment by GA-MO** [comment]
@FajneFarita 
In (App.js) Try wrap all pages like this [example with react-router](https://stackblitz.com/edit/react-skrollr-with-router)
```
<ParallaxProvider init={{smoothScrolling: true}}>
   <HashRouter>
      <Switch>
         <Route path="/howitworks" component={Howitworks}/>
      </Switch>
   <HashRouter>
</ParallaxProvider>
```

For inside (Howitworks.js) and other of pages
```
<React.Fragment>
  <Parallax data={{'data-start': 'opacity: 1; position:fixed; left:45%;','data-top': 'opacity: 0;'}}>
     <div>Scroll to see the story</div>
  </Parallax>

  <Parallax data={{.....}}
    <div> ...</div>
  </Parallax>
</React.Fragment>
```

**Comment by FajneFarita** [comment]
Nope. It did not make the library load in on routing.
Is it an issue though that App.js (https://github.com/FajneFarita/SmartGiving_web/blob/master/src/App.js) is just another container that just does the routing, while index.js imports App and renders everything into DOM? (https://github.com/FajneFarita/SmartGiving_web/blob/master/src/index.js)

**Comment by GA-MO** [comment]
@FajneFarita 
You should wrap `ParallaxProvider ` in root application the same as `Provider` of `react-redux`

if you use `redux` just do like this (index.js)

```
const AppRoot = () => (
    <Provider store={store}>
      <ParallaxProvider init={{smoothScrolling: true}}>
        {routes}
      </ParallaxProvider>
    </Provider>
)

ReactDOM.render(<AppRoot />, document.getElementById('root'));
```
So you should not use  nested `ParallaxProvider`

I just fork your project and fixed (https://stackblitz.com/edit/github-3b3pk4)

**Comment by FajneFarita** [comment]
It works! Thank you so much!!
